In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5,6]

In [3]:
a = np.array(l)

In [4]:
a

array([1, 2, 3, 4, 5, 6])

In [5]:
type(a)

numpy.ndarray

In [9]:
a1 = np.array([[1,2,3],[1,2,3]])

In [10]:
a2 = np.array([[[1,2,3],[1,2,3]]])

In [11]:
a2.ndim

3

In [12]:
a1.ndim

2

In [23]:
a3 = np.array([[[1,2,3],[3,4,5]],[[22,33,4],[5,6,7]] , [[222,22,333] , [444,666,55]]])

In [24]:
a3

array([[[  1,   2,   3],
        [  3,   4,   5]],

       [[ 22,  33,   4],
        [  5,   6,   7]],

       [[222,  22, 333],
        [444, 666,  55]]])

In [25]:
l = [1,2,3,4]

In [29]:
a = np.asarray(l)

In [28]:
m = np.matrix(l)

In [30]:
np.asanyarray(a)

array([1, 2, 3, 4])

In [31]:
np.asanyarray(m)

matrix([[1, 2, 3, 4]])

In [32]:
a

array([1, 2, 3, 4])

In [33]:
a1 = a

In [34]:
a1

array([1, 2, 3, 4])

In [35]:
a[0] = 10

In [36]:
a

array([10,  2,  3,  4])

In [37]:
a1

array([10,  2,  3,  4])

In [38]:
# this is shallow copy

In [39]:
a2 = np.copy(a)

In [40]:
a2

array([10,  2,  3,  4])

In [41]:
a2[2] = 40

In [42]:
a2

array([10,  2, 40,  4])

In [45]:
a # this is deep copy

array([10,  2,  3,  4])

In [46]:
np.fromfunction(lambda i, j : i == j ,(3,4) )

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [48]:
np.random.rand(3 ,2,3)

array([[[0.1275094 , 0.95584471, 0.91302909],
        [0.51581756, 0.18019786, 0.94719015]],

       [[0.49758641, 0.92055043, 0.1908583 ],
        [0.07583109, 0.27221565, 0.96380289]],

       [[0.37688449, 0.74938245, 0.31992997],
        [0.12297469, 0.6794344 , 0.84120096]]])

In [49]:
np.random.rand(2,3,2,3)

array([[[[0.65228588, 0.13948483, 0.13854572],
         [0.39362599, 0.8347496 , 0.21729201]],

        [[0.16407498, 0.85337942, 0.10476398],
         [0.73526316, 0.26287983, 0.3659106 ]],

        [[0.31671051, 0.51613306, 0.83401743],
         [0.83281694, 0.81640171, 0.40002   ]]],


       [[[0.48906471, 0.61555726, 0.98934069],
         [0.58253848, 0.85671439, 0.95533791]],

        [[0.60631862, 0.30798403, 0.88232411],
         [0.97794297, 0.40676404, 0.73878196]],

        [[0.02998237, 0.33635754, 0.94966159],
         [0.18246845, 0.23093158, 0.23752453]]]])

In [4]:
np.random.randn(4,4,2)

array([[[-0.51601285, -0.90412536],
        [ 0.75587845, -1.67124473],
        [ 0.2948696 ,  0.92610168],
        [ 0.02307339, -0.67270941]],

       [[-0.15930421, -0.59531948],
        [ 0.81317118, -0.09341986],
        [ 1.9619605 ,  0.58858037],
        [-0.86898921, -0.92369668]],

       [[ 0.50841689, -1.1780679 ],
        [-1.65845525, -0.27912062],
        [-1.02780466, -0.35179064],
        [-0.56117083, -1.58121374]],

       [[ 1.37951798, -0.38153642],
        [-1.32623219,  1.18855042],
        [ 0.21054054, -0.01226522],
        [ 1.77846646,  0.84369745]]])

In [12]:
d = np.random.randint(0,10, (4,4,2))

In [6]:
import pandas as pd
import numpy as np

In [13]:
pd.DataFrame(d)

ValueError: Must pass 2-d input. shape=(4, 4, 2)

In [18]:
d = d.reshape(8,4)

In [19]:
pd.DataFrame(d)

0  1  2  3
0  5  8  4  2
1  8  7  3  3
2  0  1  3  7
3  4  7  0  7
4  8  1  9  9
5  8  8  8  6
6  8  1  7  5
7  9  9  9  1

In [20]:
import numpy as np

In [21]:
range(10)

range(0, 10)

In [23]:
len(range(10))

10

In [24]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [25]:
list(range(3,10))

[3, 4, 5, 6, 7, 8, 9]

In [26]:
list(range(3,10.5))

TypeError: 'float' object cannot be interpreted as an integer

In [32]:
np.arange(5,-10.55 , -1)

array([  5.,   4.,   3.,   2.,   1.,   0.,  -1.,  -2.,  -3.,  -4.,  -5.,
        -6.,  -7.,  -8.,  -9., -10.])

In [35]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [37]:
np.logspace(1,50,10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [41]:
np.zeros((2,3,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [42]:
np.zeros((3,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [45]:
np.ones((3,4,2)) * 5

array([[[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]]])

In [47]:
np.empty((2,3))

array([[1.14281331e-313, 0.00000000e+000, 6.94360081e-310],
       [6.94360081e-310, 6.94360204e-310, 6.94360041e-310]])

In [51]:
a = np.eye(4,4)

In [53]:
a.shape

(4, 4)

In [54]:
a.size

16

In [55]:
a.ndim

2

In [56]:
a1 = np.random.randn(3,4)

In [57]:
a1

array([[ 0.65297981, -1.03719899, -0.10054358, -0.0808735 ],
       [-1.95526553,  0.01808947,  0.80590445, -0.77953082],
       [-1.12993893, -0.76627467, -1.693795  ,  0.35779572]])

In [66]:
a1[2 , 1]

-0.7662746664488735

In [63]:
a1[0:2 , 0:2]

array([[ 0.65297981, -1.03719899],
       [-1.95526553,  0.01808947]])

In [77]:
a1[[1,2] ,2:4]

array([[ 0.80590445, -0.77953082],
       [-1.693795  ,  0.35779572]])

In [82]:
np.random.randint(2,4,(3,3))

array([[3, 2, 2],
       [2, 2, 2],
       [2, 2, 3]])

In [83]:
m2 = np.random.randint(2,4,(3,3))

In [86]:
m1

array([[2, 1, 2],
       [1, 1, 1],
       [1, 2, 2]])

In [84]:
m1 = np.random.randint(1,3,(3,3))

In [81]:
m1*m2

array([[4, 6, 4],
       [2, 3, 4],
       [3, 4, 6]])

In [85]:
m1@m2

array([[12, 11, 14],
       [ 7,  7,  8],
       [12, 12, 13]])

In [87]:
pow(m1 , 3)

array([[8, 1, 8],
       [1, 1, 1],
       [1, 8, 8]])

In [88]:
np.sqrt(m1)

array([[1.41421356, 1.        , 1.41421356],
       [1.        , 1.        , 1.        ],
       [1.        , 1.41421356, 1.41421356]])